// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChiUVkjZ0zBlUGhHLaf2pkyO5zA7_8ZAI',
    appId: '1:450626116615:web:0bce62a5c2865db1bf1ea2',
    messagingSenderId: '450626116615',
    projectId: 'studdbuddy-a3158',
    authDomain: 'studdbuddy-a3158.firebaseapp.com',
    storageBucket: 'studdbuddy-a3158.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJZQwWYJ_7VsqWDeO6CtxJSuuXa7ztGc',
    appId: '1:450626116615:android:37e313132be442c2bf1ea2',
    messagingSenderId: '450626116615',
    projectId: 'studdbuddy-a3158',
    storageBucket: 'studdbuddy-a3158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvgF_lSMhSiO5bHni4QZpBDqCMuRTXuI',
    appId: '1:450626116615:ios:a738438f7290bb26bf1ea2',
    messagingSenderId: '450626116615',
    projectId: 'studdbuddy-a3158',
    storageBucket: 'studdbuddy-a3158.appspot.com',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvgF_lSMhSiO5bHni4QZpBDqCMuRTXuI',
    appId: '1:450626116615:ios:a738438f7290bb26bf1ea2',
    messagingSenderId: '450626116615',
    projectId: 'studdbuddy-a3158',
    storageBucket: 'studdbuddy-a3158.appspot.com',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChiUVkjZ0zBlUGhHLaf2pkyO5zA7_8ZAI',
    appId: '1:450626116615:web:0bce62a5c2865db1bf1ea2',
    messagingSenderId: '450626116615',
    projectId: 'studdbuddy-a3158',
    authDomain: 'studdbuddy-a3158.firebaseapp.com',
    storageBucket: 'studdbuddy-a3158.appspot.com',
  );
}
